mode = "single"

#general
runtime = 500
timestep = 0.000027
l = 100
dot_size = 5
speed_factor = 1

#single
angles = [
    90,
    30
]

#grid
grid_radius = 5
grid_angle_interval = 18
grid_axes = true

#options
#log

#trace
trace = false
trace_length = 100

#sound: when this enabled use timestep = 0.000027