mode = "graph"

#general
runtime = 500
timestep = 0.01
l = 100
dot_size = 5
speed_factor = 1

#single
angles = [
    90,
    30
]

#grid
grid_radius = 5
grid_angle_interval = 18
grid_axes = true

#trace
trace = true
trace_length = 100